_wandb:
    value:
        cli_version: 0.28.0
        e:
            aelvmfp0rg9h66y80ukavtndbcgpu450:
                codePath: wandb_track.py
                codePathLocal: wandb_track.py
                cpu_count: 12
                cpu_count_logical: 16
                cudaVersion: "13.3"
                disk:
                    /:
                        total: "500100493312"
                        used: "213055082496"
                email: danepomuceno1974@gmail.com
                executable: D:\000 PYTHON\AIM Capstone Project r11\.venv\Scripts\python.exe
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-b28dbac1-9e40-9b1e-6b63-c4aaf89dfb8e
                host: AI77
                memory:
                    total: "16869548032"
                os: Windows-11-10.0.26200-SP0
                program: D:\000 PYTHON\AIM Capstone Project r11\02 src\wandb_track.py
                python: CPython 3.14.6
                root: D:\000 PYTHON\AIM Capstone Project r11\02 src
                startedAt: "2026-07-16T02:09:21.938293Z"
                writerId: aelvmfp0rg9h66y80ukavtndbcgpu450
        m: []
        python_version: 3.14.6
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.14.6
            "5": 0.28.0
            "8":
                - 3
            "12": 0.28.0
            "13": windows-amd64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            cost_vs_threshold:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: threshold
                        "y": cost
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: Clinical Cost vs. Decision Threshold
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: cost_vs_threshold_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            feature_importance:
                panel_config:
                    fieldSettings:
                        label: feature
                        value: importance
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: Top 15 Feature Importances
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: feature_importance_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            pr_curve:
                panel_config:
                    fieldSettings:
                        class: class
                        x: recall
                        "y": precision
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Recall Curve
                        x-axis-title: Recall
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: pr_curve_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            precision_recall_vs_threshold:
                panel_config:
                    fieldSettings:
                        lineKey: lineKey
                        lineVal: lineVal
                        step: step
                    panelDefId: wandb/lineseries/v0
                    stringSettings:
                        title: Precision & Recall vs. Decision Threshold
                        xname: threshold
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: precision_recall_vs_threshold_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            roc_curve:
                panel_config:
                    fieldSettings:
                        class: class
                        x: fpr
                        "y": tpr
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: ROC Curve
                        x-axis-title: False positive rate
                        y-axis-title: True positive rate
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: roc_curve_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
learning_rate:
    value: 0.05
max_depth:
    value: 4
model:
    value: XGBClassifier
n_estimators:
    value: 300
resampling:
    value: none
scale_pos_weight:
    value: auto
threshold:
    value: 0.1
